/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelMigracaoRouteImport } from './routes/painel-migracao'
import { Route as IndexRouteImport } from './routes/index'

const PainelMigracaoRoute = PainelMigracaoRouteImport.update({
  id: '/painel-migracao',
  path: '/painel-migracao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel-migracao': typeof PainelMigracaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel-migracao': typeof PainelMigracaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel-migracao': typeof PainelMigracaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel-migracao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel-migracao'
  id: '__root__' | '/' | '/painel-migracao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelMigracaoRoute: typeof PainelMigracaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel-migracao': {
      id: '/painel-migracao'
      path: '/painel-migracao'
      fullPath: '/painel-migracao'
      preLoaderRoute: typeof PainelMigracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelMigracaoRoute: PainelMigracaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
